### ISSUE TITLE
input metadata_file

### ISSUE THREAD

**Issue by julia-pfarr** [bids-standard/eye2bids#25]
should we make the input of --metadata_file mandatory as this files contains required metadata info? i.e., in the current version of the converter I don't get ask to provide a metadata.yml file when I use the cli

**Comment by Remi-Gau** [comment]
there should be an an `--interactive` flag in the CLI you can use to make the tool ask you for the file

at the moment I am reluctant to make this mandatory before I get a better idea of how we are going to handle other input data (tobii, legacy eyetracking BIDS...)

but it is not a hill I wanna die on, so if you feel this should be mandatory, we can change that

it is early days, so we can check still revert back

**Comment by Remi-Gau** [comment]
given that it may be less annoying for users if we decide to go from mandatory to optional rather than the other way around, you may be right about this one

**Comment by julia-pfarr** [comment]
Idk, if I was a user I would prefer to not having to do a super careful check of the metadata afterwards every time but would expect the software to think _for_ me regarding this matter. But yes, we can decide at a later point.

As you said, it also depends on further developments. For example, we should also think about giving the users the choice if they want to extract an event.json file for every subject or only one time (like a prompt "do you want to generate an event.json file?" or something). Because the metadata in the event.json file can also stay the same for every subject in a small behavioral project and then they would only need it one time in a upper level directory according to BIDS' inheritance principle.
