### ISSUE TITLE
Changes in converter_json

### ISSUE THREAD

**Issue by julia-pfarr** [bids-standard/eye2bids#8]
Notes for myself

- [x] asc file is currently saved in same folder where edf file is supposed to be (sourcedata folder). Do we want to keep it that way? Or asc file in upper sub directory?
- [x] import configparser not needed, delete
- [x] insert _ before output filename for json files

**Comment by robertoostenveld** [comment]
the asc file is not part of the BIDS specification, but is (in the case of the specific Eyelink system) an intermediate sourcedata format. Hence I suggest that the BIDS specification recommends users (and hence also converters) to put it together with the edf in the sourcedata folder.
