### ISSUE TITLE
metadata.yml

### ISSUE THREAD

**Issue by julia-pfarr** [bids-standard/eye2bids#83]
So far we are accepting if the user does not provide a metadata.yml file. However, some of the metadata given by that file is required by the spec. Thus, if the user does not provide this file, required metadata is missing and the user will have an invalid dataset by the validator. I think it would be easier to either force users to provide the metadata.yml file or at least throw a warning that by not providing this metadata the dataset will not be a valid BIDS dataset and thus make problems when need to be validated. This way the user is properly informed. 
What do you think?

**Comment by julia-pfarr** [comment]
Also: we could add something saying that usually variables like "EyeTrackingMethod" or "TaskName" can be extracted by our converter but sometimes it can't due to experiment coding decisions by the individual researcher and that in this case the user can add this information in the metadata.yml file? Then we would need to change the code a bit to say "in case not extracted, take from metadata.yml"

**Comment by Remi-Gau** [comment]
whatever we choose I think that I would prefer to make sure that the output is bids valid because I have seen a number of datasets on openneuro that have TODOs in them because people never fixed things that some converters did not do.

**Comment by julia-pfarr** [comment]
Yes, me too. So we should add something that stops the conversion process if there is no metadata.yml file and display a message telling them that the converter will not run without providing the metadata.yml file
